# Generated by Django 5.0.6 on 2024-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
    ]
